config/routes.rb
Rails.application.routes.draw do
  get 'email_users/new'

  get 'users/new'
  get 'users/edit'

  root 'static_pages#home'

  get  '/about',    to:'static_pages#about'
  get  '/home',     to:'static_pages#home'
  get  '/help',     to:'static_pages#help'

  get  '/auth/:provider/callback' => 'sessions#create_by_omniauth'
  
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get  '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :plans
  resources :participations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_user.rb
class EmailUser < ApplicationRecord
  belongs_to :user, optional: true
  
  before_save { email.downcase! }
  
  validates :user_id, presence: true
  #Emailの検証
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
                    

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
  
  
  # 渡された文字列のハッシュ値を返す
  def EmailUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :plan
  belongs_to :user
  
  
  validates :user_id, presence:true
  validates :plan_id, presence:true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :participation
  mount_uploader :front_picture, PictureUploader
   
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 1000}
  
  #独自バリデーション 画像サイズ上限 5MB
  validate :picture_size
  
  
  private
  
    def picture_size
      if front_picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
has_many :plans
has_many :email_users
has_many :participations

  # validation
  # validates :twitter_id, presence:true
   validates :nickname, presence:true


  #引数に関連するユーザーが存在すればそれを返し、存在しなければ新規に作成する
  def self.find_or_create_from_auth_hash(auth_hash)
    
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    provider = auth_hash[:provider]
    image_url = auth_hash[:info][:image]
    
    User.find_or_create_by(uid: uid, provider: provider) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
    
  end
  
  # fixture向け 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: "hello, this is flow_statter app."
  end

end

app/controllers/email_users_controller.rb
class EmailUsersController < ApplicationController
  
  def new
  end

  def edit
  end
  
  def create
  end
  
  def destroy
  end
  
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    @user = current_user
    @plan = Plan.find_by_id(params[:participation][:plan_id])

    @participation = current_user.participations.find_or_initialize_by(plan_id: @plan.id)
    @participation.status = 1 if params[:commit] == "参加する"
    @participation.status = 2 if params[:commit] == "参加しない"
    @participation.save!
    
    #debugger
    redirect_to @plan
  end

  def update
    self.create
  end


  private
    def participation_params
      params.require(:participation).permit(:plan_id, user_id, unit_of_number, participatier_name)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  
  before_action :logged_in_user, only: [:new, :create, :edit]
  
  def new
    @plan = Plan.new
  end
  
  def edit
    @plan = Plan.find(params[:id])
  end
  
  def show
    @user = current_user
    @plan = Plan.find(params[:id])
    @participations = Participation.where(plan_id: @plan.id, status: 1)
    @current_participation = @participations.find_by(user_id: @user.id)
  end
  
  def create
    @user = current_user
    @plan = Plan.new(plan_params)
    if @plan.save
      flash[:success] = "プランが作成されました"
      redirect_to @plan
    else
      render 'new'
    end
  end
  
  def index
    @plans = Plan.all
  end
  
  
  private 
  
    #許可リスト
    def plan_params
      params.require(:plan).permit(:user_id, :title, :content, :status, :event_date, :front_picture )
    end
    
    # ログインしていなかったらログインを要求する
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインが必要です"
        redirect_to login_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  #Emailログイン画面
  def new
  end
  
  #Emailログイン処理
  def create
    email_user = EmailUser.find_by(email: params[:session][:email].downcase)
    if email_user && email_user.authenticate(params[:session][:password])
      user = User.find(email_user.user_id)
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Emailかパスワードが不正です'
      render 'new'
    end
  end

  # Omniauth
  def create_by_omniauth
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    if user.save
      log_in user
      redirect_to user
    else
      log_out
      flash[:danger] = "ログインできませんでした"
      redirect_to root_path
    end
  end
  
  # ログアウト処理
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  
  def new
    @user = User.new
  end
  
  private
    #create時のStrong Parameters
    def user_params
      params.require(:user).permit(:nickname, :provider, :uid, :image_url)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_users_helper.rb
module EmailUsersHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Session#log_in(user) 渡されたuserでログインする
  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  
  def logged_in?
    !current_user.nil?
  end
  
  # 現在ログイン中のユーザーを返す(いない場合はnil)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/email_users/new.html.erb
<h1>EmailUsers#new</h1>
<p>Find me in app/views/email_users/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    flow_statter 
    by <a href="http://www.michaelhartl.com/">kugyu10</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
<title><%= yield(:title) %> ふらすたった〜<フラスタ企画をお手軽に企画・管理></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class = "container">
    <%= link_to "ふらすたった〜", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "へるぷ", help_path %></li>
        <li><%= link_to "フラスタ企画一覧", "/plans" %></li>
        <li><%= link_to "新規に企画する", "/plans/new" %></li>

        <% if logged_in? %>
          <li><%= image_tag(current_user.image_url, options={ size: 50}) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to 'ログアウト', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <li><%= link_to 'Twitterでログイン', '/auth/twitter' %></li>
            <li><%= link_to 'メアドでログイン', '#' %></li>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/plans/_participation_form.html.erb
<% @current_participation = Participation.new if @current_participation == nil %>
<div class="col-sm-6">
<%= form_for(@current_participation) do |f| %>
  <%= f.label :number_of_unit %>
  <%= f.text_field :number_of_unit %>

  <%= f.label :participater_name %>
  <%= f.text_field :participater_name %>
  
  <%= f.hidden_field :plan_id, :value => @plan.id %>

  <%= f.submit "参加する", class: "btn btn-primary" %>
  <%= f.submit "参加しない", class: "btn btn-primary" %>
<% end %>
</div>

app/views/plans/index.html.erb
<% provide(:title, 'All plans') %>
<h1>All plans</h1>

<ul class="plans">
  <% @plans.each do |plan| %>
    <li>
      <%= link_to plan.title, plan %>
    </li>
  <% end %>
</ul>

app/views/plans/new.html.erb
<h1>Plan#new</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@plan) do |f| %>
    <%= render 'shared/error_messages' %>
      
      <%= f.hidden_field :user_id, :value => current_user.id %>
    
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_area :content, size: "20x20", class: 'form-control'  %>

      <%= f.label :event_date %>
      <%= f.text_field :event_date, class: 'form-control' %>
      
      <%= f.label :front_picture %>
      <span class="picture">
        <%= f.file_field :front_picture %>
      </span>
      
      <%= f.submit "Planを作成する", class: "btn btn-primary" 'image/jpeg,image/gif,image/png' %>
      
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#plan_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/plans/show.html.erb
<div class="row">
  <h1>Plans#show</h1>
  <div class="col-md-6 col-md-offset-3">
    <h2>プラン</h2>
    <span>
      <%= image_tag @plan.front_picture.url if @plan.front_picture? %>
    </span>
    <div class="row">plan_id:<%= @plan.id %>,</div>
    <div class="row">プラン内容:<%= @plan.content %>,</div>
    <div class="row">開催日:<%= @plan.event_date %></div>
    <h2>主催</h2>
      <ul class="participations">
      <li>
        <%= image_tag(@plan.user.image_url, options={ size:50}) %>
        <%= link_to "@#{@plan.user.nickname}", @plan.user %>
      </li>
      </ul>
    <h2>参加者一覧</h2>
    <ul class="participations">
      <% @participations.each do |participation| %>
      <li>
        <%= image_tag(participation.user.image_url, options={ size:50}) %>
        <%= link_to "@#{participation.user.nickname}", participation.user %> - 
        <%= participation.participater_name %>
      </li>
      <% end %>
    </ul>
    <h2>参加</2>
    <div class="row">
    <% if logged_in? %>
      <%= render 'participation_form' %>
      <p></p>
    <% else %>
      （参加状態を変更するにはログインして下さい）
    <% end %>
    <div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @plan.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @plan.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About" ) %>
<h1>About</h1>
<p>
  This is the About page .
  
  
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "よくある質問と回答" ) %>
<h1>よくある質問と回答</h1>
<p>
  作成中
</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home" ) %>
<h1>ほーむ</h1>
<p>
  ふらすたった～はフラスタ企画をお手軽に立案・管理できるWEBサービスです。
</p>
<p>
  まずはどんなフラスタ企画があがっているか、以下の一覧を見てみましょう。<br/>
  フラスタ企画を眺めるだけなら、登録などは不要です。<br/>
  <%= link_to 'フラスタ企画一覧', '/plans/' %>  
</p>
<p>
  面白そうなフラスタ企画があれば「興味あり」で企画主を応援しましょう。<br/>
  「興味あり」を押すにはTwitter認証をする必要があります。<br/>
  <%= link_to 'ここをクリック',  '/auth/twitter' %>するだけです。
</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

app/views/users/show.html.erb
<h1>User.show</h1>
<%= image_tag(@user.image_url, options={ size: 50}) %>
<%= @user.nickname %>